version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    restart: on-failure
  kt-admin-iam-service:
    container_name: kt-admin-iam-service
    image: kullapat/kt-admin-iam-service:latest
    depends_on:
      - mongo
    ports:
      - 8080:9999
    restart: on-failure